from core import run_infer_script

params = {'audio_input_path': 'assets/audios/tomas_vowels.wav', 
          'audio_output_path': 'assets/audios/tomas_vowels_output.wav', 
          'model_path': 'logs/maria-20/maria-20.pth', 
          'index_path': '', 
          'pitch': 0, 
          'index_rate': 0.75, 
          'volume_envelope': 1, 
          'protect': 0.5, 
          'hop_length': 128, 
          'f0_method': 'rmvpe', 
          'pth_path': 'logs/maria-20/maria-20.pth', 
          'split_audio': False, 
          'f0_autotune': False, 
          'f0_autotune_strength': 1, 
          'clean_audio': False, 
          'clean_strength': 0.5, 
          'export_format': 'WAV', 
          'f0_file': None, 
          'embedder_model': 'contentvec', 
          'embedder_model_custom': None, 
          'post_process': False, 
          'formant_shifting': False, 
          'formant_qfrency': 1, 
          'formant_timbre': 1, 
          'reverb': False, 
          'pitch_shift': False, 
          'limiter': False, 
          'gain': False, 
          'distortion': False, 
          'chorus': False, 
          'bitcrush': False, 
          'clipping': False, 
          'compressor': False, 
          'delay': False, 
          'reverb_room_size': 0.5, 
          'reverb_damping': 0.5, 
          'reverb_wet_level': 0.33, 
          'reverb_dry_level': 0.4, 
          'reverb_width': 1, 
          'reverb_freeze_mode': 0, 
          'pitch_shift_semitones': 0, 
          'limiter_threshold': -6, 
          'limiter_release': 0.05, 
          'gain_db': 0, 
          'distortion_gain': 25, 
          'chorus_rate': 1, 
          'chorus_depth': 0.25, 
          'chorus_delay': 7, 
          'chorus_feedback': 0, 
          'chorus_mix': 0.5, 
          'bitcrush_bit_depth': 8, 
          'clipping_threshold': -6, 
          'compressor_threshold': 0, 
          'compressor_ratio': 1, 
          'compressor_attack': 1, 
          'compressor_release': 100, 
          'delay_seconds': 0.5, 
          'delay_feedback': 0, 
          'delay_mix': 0.5, 
          'sid': 0}


run_infer_script(**params)